spring:
  redis:
    host: 192.168.223.134
    password: admin
    database: 0
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
    timeout: 2000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/red_packet?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000   # 配置一个连接池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true # 当连接空闲时，是否执行连接测试
      test-on-borrow: false # 当从连接池借用连接时，是否测试该连接
      test-on-return: false # 在连接归还到连接池时是否测试该连接
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #  配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 ,不能用log4j，不然报错：Failed to bind properties under 'spring.datasource.druid' to javax.sql.DataSource:
      filters:  stat,wall,slf4j
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties:  druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: admin
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

#mybatis
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.smart.model
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


